### PR TITLE
Add note about noqa

### PR DESCRIPTION
**Pull request by davidread**

### CODE REVIEW

**Comment by benvand** [comment]
If you can hold of merging I just want to check something with the rel-eng team.

**Comment by davidread** [comment]
Great! Can I leave it with you regarding merging it? I don't have permissions.

**Comment by benvand** [comment]
👍 I'm not sure what the rules are there either tbh! @philandstuff @davbo ?

**Comment by philandstuff** [comment]
as it's in the `manual` section, it doesn't need heavyweight approval. if you're both happy I'll just merge 👍

**Comment by benvand** [comment]
👍 Thanks @philandstuff

**Pull request merged**
