### PR TITLE
Update govuk_tech_docs to the latest version

### PR DESCRIPTION
**Pull request by timblair**
This includes a number of accessibility fixes, but one a11y issue remains, so the accessibility statement has been updated to reflect this.

### CODE REVIEW

**Comment by tombye** [comment]
I don't really do much ruby so might be wrong here but shouldn't the first commit include the `Gemfile` too?

**Comment by timblair** [comment]
Nope, the Gemfile just says `gem 'govuk_tech_docs'`. It's the Gemfile.lock that sets the version.

**Review by tombye — CHANGES_REQUESTED** [review]
The changes to the statement look good. I assume this will just pull in version `2.4.2` of `govuk_tech_docs`? it didn't for me locally running `bundle install` but testing with that version looked good.

The only change I'd like is for the `Gemfile` to lock `ffi` to `1.12`, (like https://github.com/alphagov/datagovuk-tech-docs/pull/60), to stop it blowing up for users on OSX :)

**Comment by timblair** [comment]
> I assume this will just pull in version 2.4.2 of govuk_tech_docs? it didn't for me locally running bundle install but testing with that version looked good.

Are you sure you were on the correct branch? I just did a fresh clone and `bundle install` on the `bump-tech-docs` branch and it installed `2.4.2` as expected.

> The only change I'd like is for the Gemfile to lock ffi to 1.12, (like alphagov/datagovuk-tech-docs#60), to stop it blowing up for users on OSX :)

Is this a common thing? The GDS Way repo has been using a version greater than `1.12` for a fair while. I've also never seen the problem listed in that issue (using MacOS). `ffi` is being pulled in as a dependency from `govuk_tech_docs`. If it needs pinning, it should be done there?

**Comment by tombye** [comment]
> Are you sure you were on the correct branch? I just did a fresh clone and `bundle install` on the `bump-tech-docs` branch and it installed `2.4.2` as expected.

I am sure about the branch. I just tried again and got `2.4.2` so maybe a timing thing? Either way, I'm happy this is not a problem.

>Is this a common thing? The GDS Way repo has been using a version greater than 1.12 for a fair while. I've also never seen the problem listed in that issue (using MacOS).

There are a few GDS'ers on that issue reporting experiencing it and I know of a few others doing the same on Slack a while ago. From reading the issue, it looks like it might effect people on Mohave only:

`An upgrade to MacOS10.15 should help`

>ffi is being pulled in as a dependency from govuk_tech_docs. If it needs pinning, it should be done there?

Makes sense. I'll open an issue on that repo instead.

**Review by tombye — APPROVED** [review]
Looks good to me 👍🏻

**Pull request merged**
