### PR TITLE
Mission statement clarification, standards refs

### PR DESCRIPTION
**Pull request by galund**
Update mission statement and clarify applicability outside GDS.
    
Also update some references to standards, policies and guidance.

Plus fix the Dockerfile cos there's always some yak shaving to be done.

### CODE REVIEW

**Comment by louzoid-gds** [comment]
Looking good George. Makes sense to also update the site banner (layouts/custom.erb) with this batch of changes. Ok to include?

**Comment by galund** [comment]
> Looking good. Makes sense to also update the site banner (layouts/custom.erb) with this batch of changes. Ok to include?

Yes, I'm confused why the index page has its own layout. I'll try de-duplicating...

**Comment by galund** [comment]
Have de-duplicated, I can't see anything too obvious breaking from changing the layout of the index page, but someone should probably double check for me :)

**Comment by louzoid-gds** [comment]
> Yes, I'm confused why the index page has its own layout. I'll try de-duplicating...
Quick blame defines me as the culprit but I couldn't tell you why :)

All looking good imo. I've pinged a security colleague for a thumbs up on the other content amends

**Review by Jonathan-Scott14 — COMMENTED** [review]
Looks good to me!

**Review by Jonathan-Scott14 — APPROVED** [review]

**Review by louzoid-gds — APPROVED** [review]
LGTM

**Pull request merged**
