### PR TITLE
Remove the TechOps page and add a new one for the parts that moved to…

### PR DESCRIPTION
**Pull request by deanwilson**
… CDIO

### CODE REVIEW

**Comment by louzoid-gds** [comment]
It looks like the Technical Operations page will remain (https://gds-way.cloudapps.digital/standards/technical-operations.html)
Is that intended? I'm not sure we need both and deleting it might be the way to go.
Everything else is looking good.

**Comment by timblair** [comment]
Is this a duplicate of #532?

**Comment by tomnatt** [comment]
I've updated a few minor style points and rebased (note the force push). I believe this is ready to go - can someone who hasn't committed code in this PR do a formal review please.

**Review by timblair — CHANGES_REQUESTED** [review]
Could you use a [redirect](https://github.com/alphagov/gds-way/blob/9ec1034f/config/tech-docs.yml#L38) instead of leaving the "look here instead" TechOps page?

**Review by timblair — APPROVED** [review]
But let's not block the merge. That redirect can be added as a next step.

**Comment by deanwilson** [comment]
I'll change the placeholder page to a redirect on the next review date. TechOps is still in use in a lot of places.

**Pull request merged**
